/**
 * L2 race/class id → display name.
 * Generated from L2J Mobius 12.3 Superion `PlayerClass.java` (163 classes,
 * ids 0–235). Covers everything through Death Knight / Sayha / "Maker" classes,
 * so modern characters (e.g. Ertheia Wizard #183) resolve to a real name.
 */

export const RACE_NAMES: Record<number, string> = {
  0: "Human",
  1: "Elf",
  2: "Dark Elf",
  3: "Orc",
  4: "Dwarf",
  5: "Kamael",
  6: "Ertheia",
};

export const CLASS_NAMES: Record<number, string> = {
  0: "Fighter",
  1: "Warrior",
  2: "Gladiator",
  3: "Warlord",
  4: "Knight",
  5: "Paladin",
  6: "Dark Avenger",
  7: "Rogue",
  8: "Treasure Hunter",
  9: "Hawkeye",
  10: "Mage",
  11: "Wizard",
  12: "Sorcerer",
  13: "Necromancer",
  14: "Warlock",
  15: "Cleric",
  16: "Bishop",
  17: "Prophet",
  18: "Elven Fighter",
  19: "Elven Knight",
  20: "Temple Knight",
  21: "Swordsinger",
  22: "Elven Scout",
  23: "Plains Walker",
  24: "Silver Ranger",
  25: "Elven Mage",
  26: "Elven Wizard",
  27: "Spellsinger",
  28: "Elemental Summoner",
  29: "Oracle",
  30: "Elder",
  31: "Dark Fighter",
  32: "Palus Knight",
  33: "Shillien Knight",
  34: "Bladedancer",
  35: "Assassin",
  36: "Abyss Walker",
  37: "Phantom Ranger",
  38: "Dark Mage",
  39: "Dark Wizard",
  40: "Spellhowler",
  41: "Phantom Summoner",
  42: "Shillien Oracle",
  43: "Shillien Elder",
  44: "Orc Fighter",
  45: "Orc Raider",
  46: "Destroyer",
  47: "Orc Monk",
  48: "Tyrant",
  49: "Orc Mage",
  50: "Orc Shaman",
  51: "Overlord",
  52: "Warcryer",
  53: "Dwarven Fighter",
  54: "Scavenger",
  55: "Bounty Hunter",
  56: "Artisan",
  57: "Warsmith",
  88: "Duelist",
  89: "Dreadnought",
  90: "Phoenix Knight",
  91: "Hell Knight",
  92: "Sagittarius",
  93: "Adventurer",
  94: "Archmage",
  95: "Soultaker",
  96: "Arcana Lord",
  97: "Cardinal",
  98: "Hierophant",
  99: "Eva Templar",
  100: "Sword Muse",
  101: "Wind Rider",
  102: "Moonlight Sentinel",
  103: "Mystic Muse",
  104: "Elemental Master",
  105: "Eva Saint",
  106: "Shillien Templar",
  107: "Spectral Dancer",
  108: "Ghost Hunter",
  109: "Ghost Sentinel",
  110: "Storm Screamer",
  111: "Spectral Master",
  112: "Shillien Saint",
  113: "Titan",
  114: "Grand Khavatari",
  115: "Dominator",
  116: "Doomcryer",
  117: "Fortune Seeker",
  118: "Maestro",
  123: "Male Soldier",
  124: "Female Soldier",
  125: "Trooper",
  126: "Warder",
  127: "Berserker",
  128: "Male Soulbreaker",
  129: "Female Soulbreaker",
  130: "Arbalester",
  131: "Doombringer",
  132: "Male Soul Hound",
  133: "Female Soul Hound",
  134: "Trickster",
  135: "Inspector",
  136: "Judicator",
  139: "Sigel Knight",
  140: "Tyrr Warrior",
  141: "Othell Rogue",
  142: "Yul Archer",
  143: "Feoh Wizard",
  144: "Iss Enchanter",
  145: "Wynn Summoner",
  146: "Aeore Healer",
  148: "Sigel Phoenix Knight",
  149: "Sigel Hell Knight",
  150: "Sigel Eva Templar",
  151: "Sigel Shillien Templar",
  152: "Tyrr Duelist",
  153: "Tyrr Dreadnought",
  154: "Tyrr Titan",
  155: "Tyrr Grand Khavatari",
  156: "Tyrr Maestro",
  157: "Tyrr Doombringer",
  158: "Othell Adventurer",
  159: "Othell Wind Rider",
  160: "Othell Ghost Hunter",
  161: "Othell Fortune Seeker",
  162: "Yul Sagittarius",
  163: "Yul Moonlight Sentinel",
  164: "Yul Ghost Sentinel",
  165: "Yul Trickster",
  166: "Feoh Archmage",
  167: "Feoh Soultaker",
  168: "Feoh Mystic Muse",
  169: "Feoh Storm Screamer",
  170: "Feoh Soul Hound",
  171: "Iss Hierophant",
  172: "Iss Sword Muse",
  173: "Iss Spectral Dancer",
  174: "Iss Dominator",
  175: "Iss Doomcryer",
  176: "Wynn Arcana Lord",
  177: "Wynn Elemental Master",
  178: "Wynn Spectral Master",
  179: "Aeore Cardinal",
  180: "Aeore Eva Saint",
  181: "Aeore Shillien Saint",
  182: "Ertheia Fighter",
  183: "Ertheia Wizard",
  184: "Marauder",
  185: "Cloud Breaker",
  186: "Ripper",
  187: "Stratomancer",
  188: "Eviscerator",
  189: "Sayha Seer",
  212: "Death Soldier",
  213: "Death Warrior",
  214: "Death Berserker",
  215: "Death Knight",
  216: "Sigel Death Knight",
  231: "Dwarf Maker",
  232: "Earth Maker",
  233: "Wind Maker",
  234: "Soul Maker",
  235: "Shine Maker",
};

export function classNameOf(id: number): string {
  return CLASS_NAMES[id] ?? `Class #${id}`;
}
export function raceNameOf(id: number): string {
  return RACE_NAMES[id] ?? `Race #${id}`;
}
