/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as SelectFilesRouteImport } from './routes/select-files'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CdnCacheRouteImport } from './routes/cdn-cache'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiL2BridgeRouteImport } from './routes/api/l2-bridge'
import { Route as ApiCdnSplatRouteImport } from './routes/api/cdn/$'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectFilesRoute = SelectFilesRouteImport.update({
  id: '/select-files',
  path: '/select-files',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CdnCacheRoute = CdnCacheRouteImport.update({
  id: '/cdn-cache',
  path: '/cdn-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiL2BridgeRoute = ApiL2BridgeRouteImport.update({
  id: '/api/l2-bridge',
  path: '/api/l2-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCdnSplatRoute = ApiCdnSplatRouteImport.update({
  id: '/api/cdn/$',
  path: '/api/cdn/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cdn-cache': typeof CdnCacheRoute
  '/characters': typeof CharactersRoute
  '/select-files': typeof SelectFilesRoute
  '/world': typeof WorldRoute
  '/api/l2-bridge': typeof ApiL2BridgeRoute
  '/api/cdn/$': typeof ApiCdnSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cdn-cache': typeof CdnCacheRoute
  '/characters': typeof CharactersRoute
  '/select-files': typeof SelectFilesRoute
  '/world': typeof WorldRoute
  '/api/l2-bridge': typeof ApiL2BridgeRoute
  '/api/cdn/$': typeof ApiCdnSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cdn-cache': typeof CdnCacheRoute
  '/characters': typeof CharactersRoute
  '/select-files': typeof SelectFilesRoute
  '/world': typeof WorldRoute
  '/api/l2-bridge': typeof ApiL2BridgeRoute
  '/api/cdn/$': typeof ApiCdnSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cdn-cache'
    | '/characters'
    | '/select-files'
    | '/world'
    | '/api/l2-bridge'
    | '/api/cdn/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cdn-cache'
    | '/characters'
    | '/select-files'
    | '/world'
    | '/api/l2-bridge'
    | '/api/cdn/$'
  id:
    | '__root__'
    | '/'
    | '/cdn-cache'
    | '/characters'
    | '/select-files'
    | '/world'
    | '/api/l2-bridge'
    | '/api/cdn/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CdnCacheRoute: typeof CdnCacheRoute
  CharactersRoute: typeof CharactersRoute
  SelectFilesRoute: typeof SelectFilesRoute
  WorldRoute: typeof WorldRoute
  ApiL2BridgeRoute: typeof ApiL2BridgeRoute
  ApiCdnSplatRoute: typeof ApiCdnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-files': {
      id: '/select-files'
      path: '/select-files'
      fullPath: '/select-files'
      preLoaderRoute: typeof SelectFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdn-cache': {
      id: '/cdn-cache'
      path: '/cdn-cache'
      fullPath: '/cdn-cache'
      preLoaderRoute: typeof CdnCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/l2-bridge': {
      id: '/api/l2-bridge'
      path: '/api/l2-bridge'
      fullPath: '/api/l2-bridge'
      preLoaderRoute: typeof ApiL2BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cdn/$': {
      id: '/api/cdn/$'
      path: '/api/cdn/$'
      fullPath: '/api/cdn/$'
      preLoaderRoute: typeof ApiCdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CdnCacheRoute: CdnCacheRoute,
  CharactersRoute: CharactersRoute,
  SelectFilesRoute: SelectFilesRoute,
  WorldRoute: WorldRoute,
  ApiL2BridgeRoute: ApiL2BridgeRoute,
  ApiCdnSplatRoute: ApiCdnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
